Django 로깅에서 'logging.handlers.RotatingFileHandler'를 사용할 때이 오류가 발생했습니다 :

PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'log.txt.1'


이 오류는 장고를 시작할 때 두 가지 다른 프로세스를 시작하기 때문에 나에게 발생했습니다. 두 프로세스 모두 로깅을 설정합니다. 즉, 둘 다 'settings.py'구성 파일에 정의 된 동일한 LOGGING 파일에 대한 핸들을 얻습니다.

LOGGING 변수를 설정하기 바로 전에이 설정을 settings.py 파일에 추가했습니다.

'manage.py runserver --noreload'매개 변수로 앱을 시작하면 파일 경합 문제가 해결 될 수 있습니다.